### PR TITLE
Add try catch to use function without browserify

### PR DESCRIPTION
**Pull request by frsv**
This change allow us to use this module without browserify. I think it would be better for browser only projects.

### CODE REVIEW

**Comment by gr2m** [comment]
Why did you close the PR?

**Comment by frsv** [comment]
@gr2m I've seen there was the same pull request – https://github.com/gr2m/browser-supports-log-styles/pull/19, which you've closed already. 
Actually, in my own project I can use webpack instead of browserify to avoid errors "is not defined" errors, but I still think that adding additional check to allow pass the script directly to the browser without building would be good idea. If you agree with this – I'll reopen PR

**Comment by gr2m** [comment]
Ahh I remember now. The problem is not only the `process.browser`, but also the `model.exports` on top. So downloading the built version from https://wzrd.in/standalone/browser-supports-log-styles is probably the best idea. The link is in the readme, too: https://github.com/gr2m/browser-supports-log-styles#usage

Is there a reason why you don’t want to use that built version?

**Comment by frsv** [comment]
Well, I see now. Seems like I can only use it with module builder.
Sorry, I was tired yesterday and didn't realised at once that for usage the script in npm projects I have to have module builder anyway :)

**Pull request closed without merging**
